services:
  # db:
  #   image: postgres:16
  #   container_name: sts-postgres
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   ports:
  #     - "5432:5432"
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 5s
  #     timeout: 3s
  #     retries: 10
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

  backend:
    container_name: sts-backend
    build:
      context: .
      dockerfile: Dockerfile
    # depends_on:
    #   db:
    #     condition: service_healthy
    # env_file:
    #   - .env
    ports:
      - "80:8080"
    restart: on-failure

volumes:
  pgdata: