server:
  port: 8080

spring:
  profiles:
    active: dev   # default; override via ENV: SPRING_PROFILES_ACTIVE=prod

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tradeapp}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate           # safer in dev/prod; Flyway handles migrations
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET}
            scope: [ email, profile, openid ]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

security:
  jwt:
    secret-key: ${JWT_SECRET:eb62ZM3x3psExKTIXEsmR+xk3GTU5VW4QNGejSW8CI0=}
    access-token-expiration: ${ACCESS_TTL_MS:900000}       # 15 minutes
    refresh-token-expiration: ${REFRESH_TTL_MS:604800000}  # 7 days
    allowed-skew-seconds: ${JWT_SKEW_SECONDS:60}

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
    - https://eazy-byts-trade-app.vercel.app

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.springframework.web: INFO
