spring:
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update            # Auto create/update tables in DEV
    open-in-view: false
    properties:
      hibernate.format_sql: true
      hibernate.highlight_sql: true

  flyway:
    enabled: false                # Disable Flyway for dev (avoids migration conflicts)

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  error:
    include-message: always
    include-exception: true
    include-stacktrace: ALWAYS

cors:
  allowed-origins:
    - http://localhost:5173
    - https://eazy-byts-trade-app.vercel.app

logging:
  level:
    root: INFO
    com.sts.backend: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
