server:
  port: 8080

spring:
  profiles:
    active: dev   # default to the dev profile; remove if you prefer setting via env

  datasource:
    url: jdbc:postgresql://localhost:5432/tradeapp
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate         # prod-safe; schema must exist
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: [ email, profile, openid ]
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

security:
  jwt:
    secret-key: eb62ZM3x3psExKTIXEsmR+xk3GTU5VW4QNGejSW8CI0=
    access-token-expiration: 900000        # 15 min
    refresh-token-expiration: 604800000    # 7 days
    allowed-skew-seconds: 60

cors:
  allowed-origins:
    - http://localhost:5173
    - http://localhost:5174
